apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-configs
  namespace: <NAMESPACE>
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: <STORAGECLASSNAME>

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-reports
  namespace: <NAMESPACE>
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: <STORAGECLASSNAME>