apiVersion: v1
kind: Service
metadata:
  name: {{ include "inspection-center.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "inspection-center.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "inspection-center.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
