apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  labels:
    app.kubernetes.io/name: {{ include "inspection-center.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.frontend.service.type | default "NodePort" }}
  selector:
    app.kubernetes.io/name: {{ include "inspection-center.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      {{- if eq (.Values.frontend.service.type | default "NodePort") "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort | default 0 }}
      {{- end }}
