apiVersion: v1
kind: Service
metadata:
  name: {{ include "inspection-center.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "inspection-center.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "inspection-center.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort | default 0 }}
