{{- if and .Values.licenseSecret.create .Values.licenseSecret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-license" (include "inspection-center.fullname" .)) .Values.licenseSecret.name }}
  labels:
    app.kubernetes.io/name: {{ include "inspection-center.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.licenseSecret.key }}: {{ .Values.licenseSecret.value | quote }}
{{- end }}
