imagePullSecrets: []

serviceAccount:
  create: true
  name: ""

backend:
  replicaCount: 1
  image:
    repository: 192.168.10.51/inspect-k8s/backend
    tag: dev-v0.1.53
    pullPolicy: Always
  env:
    - name: MYSQL_HOST
      value: 192.168.10.184
    - name: MYSQL_PORT
      value: "3306"
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PASSWORD
      value: root
    - name: MYSQL_DATABASE
      value: demo
    - name: LICENSE_SECRET
      value: demo-secret
  persistence:
    enabled: true
    create: true
    existingClaim: ""
    name: backend-data
    storageClassName: local-path
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    mountPath: /app/data
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

frontend:
  replicaCount: 1
  image:
    repository: 192.168.10.51/inspect-k8s/frontend
    tag: dev-v0.1.53
    pullPolicy: Always
  env:
    - name: API_SERVER
      value: http://backend:8000
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30001
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
