imagePullSecrets: []

serviceAccount:
  create: true
  name: ""

backend:
  replicaCount: 1
  image:
    repository: 192.168.10.51/inspect-k8s/backend
    tag: dev-v0.1.53
    pullPolicy: Always
  env:
    MYSQL_HOST: 192.168.10.184
    MYSQL_PORT: "3306"
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: demo
    LICENSE_SECRET: demo-secret
  persistence:
    enabled: true
    create: true
    existingClaim: ""
    name: backend-data
    storageClassName: local-path
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    mountPath: /app/data
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

frontend:
  replicaCount: 1
  image:
    repository: 192.168.10.51/inspect-k8s/frontend
    tag: dev-v0.1.53
    pullPolicy: Always
  env:
    API_SERVER: http://backend:8000
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30001
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
