apiVersion: v1
kind: Config
clusters:
- name: "inspect-demo"
  cluster:
    server: "https://192.168.2.254/k8s/clusters/c-m-m449cplw"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GMyTURVeApPREUyTURBZUZ3MHlOVEV3TVRVd09EUTVNakJhRncwek5URXdNVE13T0RRNU1qQmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56WXdOVEU0TVRZd01Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRS9sRkswVjFYcmNZeApQa0pOUG9rdzdQRVgwbGw5MTA2R05oNGJIM\
      kFnREV4RTA2amtCZjJ3bjBmamRBbGs1dlBHeDJhK09zeDFRWElvCjg5cHBJMWw0S0tOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGQ\
      UN3NGpTREx0Tk5lZXltdm1xMStkNVFISVorTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUQrcgpFL\
      0ladWpOdDI0Q003bmZYYUVCS01NeXNGWWVuLzVGYW1xVHJqOUNUQWlFQW9kdUoxZjhGOTdBTnJCS\
      1hxS3h2CmxBUEpLVDZrVlpJZUx1b0hSamFJbEJVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "inspect-demo"
  user:
    token: "kubeconfig-user-24q266klth:7r7zdmc4l64cg9wdkx94dt7jvskbjq25kq2647dt4gfd8pw8tnlsjf"


contexts:
- name: "inspect-demo"
  context:
    user: "inspect-demo"
    cluster: "inspect-demo"

current-context: "inspect-demo"
