apiVersion: v1
kind: Config
clusters:
- name: "cluster01"
  cluster:
    server: "https://192.168.10.50/k8s/clusters/c-m-wlv657wn"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyRENDQ\
      XBTZ0F3SUJBZ0lVVEhSRGJEU09sc1A5Uk1jcDlsYkliT2N1bGJjd0RRWUpLb1pJaHZjTkFRRUwKQ\
      lFBd2JqRUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0ZOb1pXNTZhR1Z1TVJJd0VBWURWU\
      VFIRXdsSApkV0Z1WjJSdmJtY3hFREFPQmdOVkJBb1RCM3BvYVhOMVlXNHhFakFRQmdOVkJBc1RDV\
      3QxWW1WeWJtVjBjekVTCk1CQUdBMVVFQXhNSlkyRjBkR3hsTFdOaE1CNFhEVEkwTVRFd01qQXlOV\
      FV3TUZvWERUTTBNVEF6TVRBeU5UVXcKTUZvd2JqRUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQ\
      WdUQ0ZOb1pXNTZhR1Z1TVJJd0VBWURWUVFIRXdsSApkV0Z1WjJSdmJtY3hFREFPQmdOVkJBb1RCM\
      3BvYVhOMVlXNHhFakFRQmdOVkJBc1RDV3QxWW1WeWJtVjBjekVTCk1CQUdBMVVFQXhNSlkyRjBkR\
      3hsTFdOaE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQXY1MmtzU\
      mtoa0tCTEovSENkeXQ2YmZldXhGS1A2MmxVOGtSRzhHYUcyT2x1TUZTMTdHUE53aGY0eHYzYgp1e\
      XVvc0ZEMkRHc0NvcHliLy94WFc0V21BV0NUbGZDb0FOZ3g4S3hXOU51Y1grc1g3em5jRGx5TXFIS\
      FZBd0RmCmd6YUdaaWNFQko2V2lVRHFrVmRISmhwWDhwbFo3WUtrYlM3UVV4TkxGeU9SNDkrS1lPT\
      UUzUVNuUWFzT05vcVoKWnYrcGZIOERsZk9ob2lZSHgvcnRaVCtlVXlJWW91VVBOL2QxNFVyYXByb\
      Dcxd3c1L0YyUXdUYXJHblFQWC8yYgp6eTkycTRYbEFNMGhvTjR6ZklyY2Z2L1U4alVPRlZCayt1T\
      TFmT3pPRTZSSjJzOUMwVlo3b0dNeUEyMzhJOUZMCmlKeEMzemZ5bFlnVExWRDU5M21MUHBXdk1RS\
      URBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96Q\
      WRCZ05WSFE0RUZnUVV4K0FueEdZZ2JlR2U4Uk1waVRqemtNdmFXOU13RFFZSgpLb1pJaHZjTkFRR\
      UxCUUFEZ2dFQkFCeVFDSDRYRUJndWFNR1BJaGdTN0tPdllZZ0xUcVNsUWJiV3ZEOUVRL0FNCndjR\
      C9Pc2pGU0tjK0hWNWhoV2ZDMHpoWWJjRHdvZ2k2b0M5MjljbHRRcEhXdlNXdnNUTHJFQjhLaFRzU\
      HBtcDEKVlF4Y2tmbktpRDljd1dodEwxalJNcTNMZHhjMHI3RVNzSzJyeXBkWTBKNmV1TmZudGZuN\
      k8zRFhkU28zSExhSApzbVc3ZWlXOHZNb3U4RWNZYXFBOHV4VE1Ja1Y1L0luenBCdG15eC9oWm90a\
      mJqVU9PMk52c3JYdys5VVhSYmIxCk54dDBGQzc3NzI2YndCM284OEljcjlVSzFDcCtkd3E2SEQzb\
      FA5RDV3cDZQalUyaXExeVYyWm1qQjliWEdIcTEKR0dYTlZNRG9xZFl6R1hEZG5wNDZoSk5nSzFrN\
      1B3T2k1RWZGNGNXRmdxdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="

users:
- name: "cluster01"
  user:
    token: "kubeconfig-user-b6t88j99t4:gg4z9t27xj9gbkvhsht9hdsfcxql6x6n9hsxzwjnmx9l7qxwdlj4lg"


contexts:
- name: "cluster01"
  context:
    user: "cluster01"
    cluster: "cluster01"

current-context: "cluster01"
